siteTitle="Knotel"
baseColor = "#5a92bf"
linkPrefix = "/knotel-docs"

docPages = [
  "/docs/",
  "/docs/getting-started/",
  "/docs/how-to-run/",
  "/docs/some-react-code/",
  "/docs/the-next-step/",
  "/docs/conclusion/",
]
